server:
  port: 9005

spring:
  profiles:
    active: local
  application:
    name: es
  elasticsearch:
    uris: 192.168.150.128:9300
    username:
    password:
    connection-timeout: 1000
    read-timeout: 1000